import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.scss';
import { SearchProvider } from '@/contexts/search-context';
import Header from '@/components/header/header';

const noto = Noto_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <Header />
        <SearchProvider>{children}</SearchProvider>
      </body>
    </html>
  );
}
